name: flutter_app_bloc
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  test: ^1.21.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
